# Copyright (c) 2024 Liam Beguin <liambeguin@gmail.com>
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y

CONFIG_SHELL=y
CONFIG_SHELL_HISTORY=y
CONFIG_GPIO_SHELL=y

CONFIG_SPI=y
CONFIG_SPI_SHELL=y

CONFIG_BME280=y
CONFIG_SENSOR=y
CONFIG_SENSOR_SHELL=y
