# Copyright (c) 2024 Liam Beguin <liambeguin@gmail.com>
# SPDX-License-Identifier: Apache-2.0

CONFIG_EARLY_CONSOLE=y
CONFIG_LOG=y

CONFIG_SHELL=y
CONFIG_SHELL_HISTORY=y
CONFIG_GPIO_SHELL=y

CONFIG_SPI=y
CONFIG_SPI_SHELL=y

CONFIG_NETWORKING=y
CONFIG_NET_SHELL=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_IPV6=n
CONFIG_NET_6LO=n

CONFIG_IEEE802154=y
CONFIG_IEEE802154_ADF702X=y

CONFIG_NSP=y
CONFIG_NSP_PACKET_LISTENER=y
CONFIG_NSP_SIMPLE_EP=n
CONFIG_NET_L2_NSP=y
CONFIG_NSP_SOCK_TX_MASK=0x20

CONFIG_LOG_PROCESS_TRIGGER_THRESHOLD=1
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_IEEE802154_DRIVER_LOG_LEVEL_INF=y



# debug
CONFIG_COMPILER_SAVE_TEMPS=y
CONFIG_THREAD_NAME=y
CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_DEBUG_THREAD_INFO=y
