# Copyright (c) 2024 Liam Beguin <liambeguin@gmail.com>
# SPDX-License-Identifier: Apache-2.0

CONFIG_EARLY_CONSOLE=y
CONFIG_LOG=y

CONFIG_SHELL=y
CONFIG_SHELL_HISTORY=y
CONFIG_GPIO_SHELL=y

CONFIG_SPI=y
CONFIG_SPI_SHELL=y

CONFIG_NETWORKING=y
CONFIG_NET_PKT_RX_COUNT=6
CONFIG_NET_PKT_TX_COUNT=6
CONFIG_NET_BUF_DATA_SIZE=128

CONFIG_IEEE802154=y
CONFIG_IEEE802154_ADF702X=y

CONFIG_TEST_RANDOM_GENERATOR=y

# if raw_mode
# # this disables net_recv_data()
CONFIG_IEEE802154_RAW_MODE=y
#
# elif IEEE802154_L2
#
# CONFIG_TEST_RANDOM_GENERATOR=y
# CONFIG_NET_L2_IEEE802154=y
# CONFIG_NET_L2_IEEE802154_SHELL=y
# CONFIG_NET_SHELL=y
# CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_LOG=y
# CONFIG_NET_IF_MAX_IPV6_COUNT=2
# 
# elif DUMMY_L2
#
# CONFIG_NET_L2_DUMMY=y
# CONFIG_NET_SHELL=y
# CONFIG_NET_CONFIG_SETTINGS=y
# CONFIG_NET_LOG=y
# CONFIG_NET_IF_MAX_IPV6_COUNT=2
# endif
